name: CI/CD Push to Portfolio

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run docs:build

      # --- NEW STEP: PUSH TO ANOTHER REPO ---
      - name: Push dist to myWebPortfolios
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # This pulls the secret you created in Step 2
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'wang0857'
          destination-repository-name: 'myWebPortfolios'
          user-email: 'roufangwang@gmail.com'
          target-branch: 'main'
          target-directory: ''
